[package]
name = "workflow"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[package.metadata.release]
release = false

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true, features = ["env", "derive"] }
deadpool-redis = { workspace = true }
futures = { workspace = true}
hex = { workspace = true }
nix = { workspace = true }
redis = { workspace = true, features = ["tokio-rustls-comp", "tokio-comp"] }
risc0-zkvm = { workspace = true, default-features = false, features = ["prove", "unstable"] }
serde = { workspace = true }
serde_json = { workspace = true }
signal-hook = { workspace = true }
sqlx = { workspace = true }
nvml-wrapper = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true }
taskdb = { workspace = true }
workflow-common = { workspace = true }
grpc-client = { workspace = true }

[[bin]]
name = "agent"
path = "src/bin/agent.rs"

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
