[api]
host = "0.0.0.0"
port = 8080
user_id = "local_user"

[database]
url = "postgres://bento:bentopassword@localhost:5432/taskdb"

[redis]
url = "redis://localhost:6379"

[minio]
endpoint = "localhost:9000"
access_key = "minioadmin"
secret_key = "minioadmin"
use_ssl = false
bucket = "proofs"

[agents]
executor = true
gpu = true
aux = true
snark = false

[proof]
output_dir = "./proofs"
segment_size = 1000000  # Adjust based on your GPU VRAM