[package]
name = "prover"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
tokio = { workspace = true }
sqlx = { workspace = true }
risc0-zkvm = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
tracing = "0.1"
tracing-subscriber = "0.3"