database:
  url: "postgres://localhost/local_bento"
redis:
  url: "redis://localhost"
storage:
  proof_output_dir: "./proofs"
compute_configs:
  - id: 0
    segment_size: 1048576  # 2^20, smaller for CPU
    use_cpu: true
  - id: 1
    segment_size: 1048576
    use_cpu: true